name: dsd
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - bzip2=1.0.8
  - ca-certificates=2026.1.4
  - certifi=2024.8.30
  - cftime=1.6.2
  - curl=8.18.0
  - cycler=0.11.0
  - fonttools=4.38.0
  - freetype=2.14.1
  - hdf4=4.2.15
  - hdf5=1.12.2
  - icu=73.2
  - jpeg=9e
  - kiwisolver=1.4.4
  - krb5=1.21.3
  - lcms2=2.14
  - lerc=4.0.0
  - libaec=1.1.4
  - libblas=3.11.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.11.0
  - libclang13=21.1.8
  - libcurl=8.18.0
  - libdeflate=1.14
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libhwloc=2.12.1
  - libiconv=1.18
  - libkrb5=1.21.3
  - liblapack=3.11.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnetcdf=4.8.1
  - libpng=1.6.53
  - libpq=17.6
  - libsqlite=3.51.1
  - libssh2=1.11.1
  - libtiff=4.4.0
  - libwebp-base=1.6.0
  - libxcb=1.13
  - libxml2=2.13.9
  - libzip=1.11.2
  - libzlib=1.3.1
  - llvm-openmp=21.1.8
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - matplotlib=3.5.3
  - matplotlib-base=3.5.3
  - mkl=2025.3.0
  - msys2-conda-epoch=20160418
  - munkres=1.1.4
  - netcdf4=1.6.1
  - numpy=1.21.6
  - openjpeg=2.5.0
  - openssl=3.6.0
  - packaging=23.2
  - pandas=1.3.5
  - pillow=9.2.0
  - pip=24.0
  - pthread-stubs=0.4
  - pyparsing=3.1.4
  - pyqt=5.15.4
  - pyqt5-sip=12.9.0
  - python=3.7.12
  - python-dateutil=2.9.0
  - python_abi=3.7
  - pytmatrix=0.3.2
  - pytz=2024.2
  - qt-main=5.15.2
  - scipy=1.7.3
  - setuptools=59.8.0
  - sip=6.5.1
  - six=1.16.0
  - sqlite=3.51.1
  - tbb=2022.3.0
  - tk=8.6.13
  - toml=0.10.2
  - tornado=6.2
  - typing-extensions=4.7.1
  - typing_extensions=4.7.1
  - ucrt=10.0.26100.0
  - unicodedata2=14.0.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vcomp14=14.44.35208
  - versioneer=0.29
  - vs2015_runtime=14.44.35208
  - wheel=0.42.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.8.1
  - xz-tools=5.8.1
  - zlib=1.3.1
  - zstd=1.5.7
prefix: C:\Users\lihb\anaconda3\envs\dsd
